steps:
#  - name: 'gcr.io/cloud-builders/gradle:5.6.2-jdk-8'
#    entrypoint: bash
#    args: ['./scripts/build.bash']
#    volumes:
#      - name: 'jar'
#        path: /jar
#  - name: 'gcr.io/cloud-builders/gcloud'
#    entrypoint: bash
#    args: ['./scripts/deploy.bash']
#    volumes:
#      - name: 'jar'
#        path: /jar

  - name: gcr.io/$PROJECT_ID/remote-builder
    env:
      - COMMAND=sudo ls -al